// index.js - this file should be automatically generated by nfx cli tool

// createTask
const nfx = require('nfx-framework');

const appModule = require('./app'),
      functionModule = require('./functions/createTask');

exports.handler = nfx.wrap.amazon(functionModule, appModule, {});
