swagger: '2.0'

info:
  version: "0.0.1"
  title: nfx_todo
  description: test nfx serverless app project

x-nfx:
  defaults:
    ram: 128
    timeout: 3

paths:
  /tasks:
    post:
      description: |
        Creates a new `task` object.
      parameters:
        -
          name: title
          in: formData
          description: Title of `task`
          required: true
          type: string
      responses:
        201:
          description: Successful response
          schema:
            title: Task
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              done:
                type: boolean
      x-nfx:
        handler: app/createTask
        ram: 128
        timeout: 3

    get:
      description: |
        Gets `task` objects.
      responses:
        200:
          description: Successful response
          schema:
            title: Tasks
            type: array
            items:
              title: Task
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                done:
                  type: boolean

      x-nfx:
        handler: app/listTasks

  /tasks/{taskId}:
    patch:
      description: |
        Updates an existing `task` object.
      parameters:
        -
          name: taskId
          in: path
          description: ID of `task`
          required: true
          type: string
        -
          name: title
          in: formData
          description: Title of `task`
          required: false
          type: string
        -
          name: done
          in: formData
          description: Whether or not `task` is done
          required: false
          type: boolean
      responses:
        200:
          description: Successful response
          schema:
            title: Task
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              done:
                type: boolean
      x-nfx:
        handler: app/updateTask

    delete:
      description: |
        Deletes an existing `task` object.
      parameters:
        -
          name: taskId
          in: path
          description: ID of `task`
          required: true
          type: string
      responses:
        204:
          description: Successful response
      x-nfx:
        handler: app/deleteTask
